"""initial schema

Revision ID: 1a073f496248
Revises:
Create Date: 2026-08-21 06:50:49.648827+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1a073f496248"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ---------------------------------------------------------------------------
# Append-only protection for `audit_events`.
#
# The repository layer exposes no update/delete methods, but the audit trail is
# a compliance artefact: enforce immutability in the database as well, so no
# ORM bug, migration, or ad-hoc psql session can rewrite history.
# ---------------------------------------------------------------------------

# Enum types are created implicitly by `create_table`; dropping the tables does
# not remove them, so `downgrade` has to clean them up for a re-`upgrade` to work.
ENUM_TYPES = (
    "actor_type",
    "agent_run_status",
    "approval_decision_type",
    "asset_status",
    "criticality",
    "evidence_type",
    "part_check_status",
    "production_impact",
    "proposal_status",
    "severity",
    "work_order_status",
    "workflow_status",
)

AUDIT_GUARD_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION reject_audit_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'audit_events is append-only: % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

AUDIT_GUARD_TRIGGER_SQL = """
CREATE TRIGGER trg_audit_events_append_only
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("plant_name", sa.String(length=255), nullable=False),
        sa.Column("line_name", sa.String(length=255), nullable=False),
        sa.Column(
            "criticality",
            sa.Enum("low", "medium", "high", "critical", name="criticality"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "operational",
                "degraded",
                "down",
                "maintenance",
                "decommissioned",
                name="asset_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("asset_code", name=op.f("uq_assets_asset_code")),
    )
    op.create_index("ix_assets_asset_code", "assets", ["asset_code"], unique=False)
    op.create_index(
        "ix_assets_plant_name_line_name", "assets", ["plant_name", "line_name"], unique=False
    )
    op.create_index("ix_assets_status", "assets", ["status"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "major", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "workflow_status",
            sa.Enum(
                "detected",
                "diagnosing",
                "diagnosed",
                "proposed",
                "awaiting_approval",
                "approved",
                "rejected",
                "scheduled",
                "in_progress",
                "resolved",
                "cancelled",
                name="workflow_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_incidents_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("trace_id", name=op.f("uq_incidents_trace_id")),
    )
    op.create_index("ix_incidents_asset_id", "incidents", ["asset_id"], unique=False)
    op.create_index(
        "ix_incidents_asset_id_workflow_status",
        "incidents",
        ["asset_id", "workflow_status"],
        unique=False,
    )
    op.create_index("ix_incidents_detected_at", "incidents", ["detected_at"], unique=False)
    op.create_index("ix_incidents_severity", "incidents", ["severity"], unique=False)
    op.create_index("ix_incidents_trace_id", "incidents", ["trace_id"], unique=False)
    op.create_index("ix_incidents_workflow_status", "incidents", ["workflow_status"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "timed_out",
                "cancelled",
                name="agent_run_status",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_agent_runs_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_agent_runs_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index("ix_agent_runs_incident_id", "agent_runs", ["incident_id"], unique=False)
    op.create_index("ix_agent_runs_started_at", "agent_runs", ["started_at"], unique=False)
    op.create_index("ix_agent_runs_status", "agent_runs", ["status"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum("human", "agent", "system", "external_system", name="actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "event_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_audit_events_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"], unique=False)
    op.create_index("ix_audit_events_incident_id", "audit_events", ["incident_id"], unique=False)
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False)
    op.create_index("ix_audit_events_trace_id", "audit_events", ["trace_id"], unique=False)
    op.create_index(
        "ix_audit_events_trace_id_occurred_at",
        "audit_events",
        ["trace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "maintenance_proposals",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("proposed_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("rul_margin_days", sa.Float(), nullable=True),
        sa.Column(
            "production_impact",
            sa.Enum("none", "low", "medium", "high", "line_stop", name="production_impact"),
            nullable=False,
        ),
        sa.Column("crew_available", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "awaiting_approval",
                "approved",
                "rejected",
                "superseded",
                "cancelled",
                name="proposal_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_hours > 0", name=op.f("ck_maintenance_proposals_duration_positive")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_maintenance_proposals_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_proposals")),
    )
    op.create_index(
        "ix_maintenance_proposals_incident_id",
        "maintenance_proposals",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        "ix_maintenance_proposals_proposed_start_at",
        "maintenance_proposals",
        ["proposed_start_at"],
        unique=False,
    )
    op.create_index(
        "ix_maintenance_proposals_status", "maintenance_proposals", ["status"], unique=False
    )
    op.create_table(
        "work_orders",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("external_reference", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "open",
                "dispatched",
                "in_progress",
                "completed",
                "cancelled",
                name="work_order_status",
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_work_orders_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
    )
    op.create_index(
        "ix_work_orders_external_reference", "work_orders", ["external_reference"], unique=False
    )
    op.create_index("ix_work_orders_incident_id", "work_orders", ["incident_id"], unique=False)
    op.create_index("ix_work_orders_status", "work_orders", ["status"], unique=False)
    op.create_table(
        "approval_decisions",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("pending", "approved", "rejected", "expired", name="approval_decision_type"),
            nullable=False,
        ),
        sa.Column("approver_id", sa.String(length=128), nullable=True),
        sa.Column("approver_name", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approval_token_hash", sa.String(length=128), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_approval_decisions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["maintenance_proposals.id"],
            name=op.f("fk_approval_decisions_proposal_id_maintenance_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_decisions")),
    )
    op.create_index(
        "ix_approval_decisions_decision", "approval_decisions", ["decision"], unique=False
    )
    op.create_index(
        "ix_approval_decisions_incident_id", "approval_decisions", ["incident_id"], unique=False
    )
    op.create_index(
        "ix_approval_decisions_incident_id_decision",
        "approval_decisions",
        ["incident_id", "decision"],
        unique=False,
    )
    op.create_index(
        "ix_approval_decisions_proposal_id", "approval_decisions", ["proposal_id"], unique=False
    )
    op.create_index(
        "ix_approval_decisions_token_expires_at",
        "approval_decisions",
        ["token_expires_at"],
        unique=False,
    )
    op.create_table(
        "diagnoses",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("failure_mode_code", sa.String(length=64), nullable=False),
        sa.Column("fmea_reference", sa.String(length=128), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("rul_estimate_days", sa.Float(), nullable=True),
        sa.Column("rul_ci_low_days", sa.Float(), nullable=True),
        sa.Column("rul_ci_high_days", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_diagnoses_confidence_range")
        ),
        sa.CheckConstraint(
            "rul_ci_low_days IS NULL OR rul_ci_high_days IS NULL OR rul_ci_low_days <= rul_ci_high_days",
            name=op.f("ck_diagnoses_rul_ci_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_diagnoses_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_diagnoses_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
    )
    op.create_index("ix_diagnoses_agent_run_id", "diagnoses", ["agent_run_id"], unique=False)
    op.create_index(
        "ix_diagnoses_failure_mode_code", "diagnoses", ["failure_mode_code"], unique=False
    )
    op.create_index("ix_diagnoses_incident_id", "diagnoses", ["incident_id"], unique=False)
    op.create_table(
        "part_checks",
        sa.Column("maintenance_proposal_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "available",
                "backordered",
                "unavailable",
                "reserved",
                name="part_check_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lead_time_days IS NULL OR lead_time_days >= 0",
            name=op.f("ck_part_checks_lead_time_non_negative"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_part_checks_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["maintenance_proposal_id"],
            ["maintenance_proposals.id"],
            name=op.f("fk_part_checks_maintenance_proposal_id_maintenance_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_checks")),
    )
    op.create_index(
        "ix_part_checks_maintenance_proposal_id",
        "part_checks",
        ["maintenance_proposal_id"],
        unique=False,
    )
    op.create_index("ix_part_checks_sku", "part_checks", ["sku"], unique=False)
    op.create_index("ix_part_checks_status", "part_checks", ["status"], unique=False)
    op.create_table(
        "technician_outcomes",
        sa.Column("work_order_id", sa.UUID(), nullable=False),
        sa.Column("diagnosis_confirmed", sa.Boolean(), nullable=True),
        sa.Column("actual_finding", sa.Text(), nullable=True),
        sa.Column(
            "parts_used_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("technician_note", sa.Text(), nullable=True),
        sa.Column("repair_duration_hours", sa.Float(), nullable=True),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_technician_outcomes_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_outcomes")),
    )
    op.create_index(
        "ix_technician_outcomes_captured_at", "technician_outcomes", ["captured_at"], unique=False
    )
    op.create_index(
        "ix_technician_outcomes_diagnosis_confirmed",
        "technician_outcomes",
        ["diagnosis_confirmed"],
        unique=False,
    )
    op.create_index(
        "ix_technician_outcomes_work_order_id",
        "technician_outcomes",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "evidence_items",
        sa.Column("diagnosis_id", sa.UUID(), nullable=False),
        sa.Column("signal_name", sa.String(length=128), nullable=False),
        sa.Column("observed_value", sa.Float(), nullable=True),
        sa.Column("baseline_value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "sensor_reading",
                "spectral_feature",
                "threshold_breach",
                "trend",
                "maintenance_history",
                "manual_observation",
                name="evidence_type",
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("source_reference", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "weight IS NULL OR (weight >= 0 AND weight <= 1)",
            name=op.f("ck_evidence_items_weight_range"),
        ),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
            name=op.f("fk_evidence_items_diagnosis_id_diagnoses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_index(
        "ix_evidence_items_diagnosis_id", "evidence_items", ["diagnosis_id"], unique=False
    )
    op.create_index(
        "ix_evidence_items_signal_name", "evidence_items", ["signal_name"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(AUDIT_GUARD_FUNCTION_SQL)
    op.execute(AUDIT_GUARD_TRIGGER_SQL)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_evidence_items_signal_name", table_name="evidence_items")
    op.drop_index("ix_evidence_items_diagnosis_id", table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index("ix_technician_outcomes_work_order_id", table_name="technician_outcomes")
    op.drop_index("ix_technician_outcomes_diagnosis_confirmed", table_name="technician_outcomes")
    op.drop_index("ix_technician_outcomes_captured_at", table_name="technician_outcomes")
    op.drop_table("technician_outcomes")
    op.drop_index("ix_part_checks_status", table_name="part_checks")
    op.drop_index("ix_part_checks_sku", table_name="part_checks")
    op.drop_index("ix_part_checks_maintenance_proposal_id", table_name="part_checks")
    op.drop_table("part_checks")
    op.drop_index("ix_diagnoses_incident_id", table_name="diagnoses")
    op.drop_index("ix_diagnoses_failure_mode_code", table_name="diagnoses")
    op.drop_index("ix_diagnoses_agent_run_id", table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index("ix_approval_decisions_token_expires_at", table_name="approval_decisions")
    op.drop_index("ix_approval_decisions_proposal_id", table_name="approval_decisions")
    op.drop_index("ix_approval_decisions_incident_id_decision", table_name="approval_decisions")
    op.drop_index("ix_approval_decisions_incident_id", table_name="approval_decisions")
    op.drop_index("ix_approval_decisions_decision", table_name="approval_decisions")
    op.drop_table("approval_decisions")
    op.drop_index("ix_work_orders_status", table_name="work_orders")
    op.drop_index("ix_work_orders_incident_id", table_name="work_orders")
    op.drop_index("ix_work_orders_external_reference", table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index("ix_maintenance_proposals_status", table_name="maintenance_proposals")
    op.drop_index("ix_maintenance_proposals_proposed_start_at", table_name="maintenance_proposals")
    op.drop_index("ix_maintenance_proposals_incident_id", table_name="maintenance_proposals")
    op.drop_table("maintenance_proposals")
    op.drop_index("ix_audit_events_trace_id_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_trace_id", table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_incident_id", table_name="audit_events")
    op.drop_index("ix_audit_events_event_type", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_agent_runs_status", table_name="agent_runs")
    op.drop_index("ix_agent_runs_started_at", table_name="agent_runs")
    op.drop_index("ix_agent_runs_incident_id", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_incidents_workflow_status", table_name="incidents")
    op.drop_index("ix_incidents_trace_id", table_name="incidents")
    op.drop_index("ix_incidents_severity", table_name="incidents")
    op.drop_index("ix_incidents_detected_at", table_name="incidents")
    op.drop_index("ix_incidents_asset_id_workflow_status", table_name="incidents")
    op.drop_index("ix_incidents_asset_id", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_assets_status", table_name="assets")
    op.drop_index("ix_assets_plant_name_line_name", table_name="assets")
    op.drop_index("ix_assets_asset_code", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
